#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Nov 11 09:34:39 -03 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 264ff1da682e4132b0828177e9bb1e43 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_fibonacci_behav xil_defaultlib.tb_fibonacci -log elaborate.log"
xelab -wto 264ff1da682e4132b0828177e9bb1e43 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_fibonacci_behav xil_defaultlib.tb_fibonacci -log elaborate.log

