#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Nov 09 07:42:17 -03 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 219fe780544a415aaf087b36a586e9c8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot FSM_alt_tb_behav xil_defaultlib.FSM_alt_tb -log elaborate.log"
xelab -wto 219fe780544a415aaf087b36a586e9c8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot FSM_alt_tb_behav xil_defaultlib.FSM_alt_tb -log elaborate.log

