#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Nov 05 03:48:25 -03 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto eb42de66d4d740b88209ffc52b98c84b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot sync_count_tb_behav xil_defaultlib.sync_count_tb -log elaborate.log"
xelab -wto eb42de66d4d740b88209ffc52b98c84b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot sync_count_tb_behav xil_defaultlib.sync_count_tb -log elaborate.log

